import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import cls from "../styles/Home.module.scss"
import Header from "@/components/header/header";
import { Swiper, SwiperSlide } from 'swiper/react';
import "swiper/css"

const inter = Inter({ subsets: ['latin'] })

export default function Home(props:any) {
  return (
    <>
      <Head>
        <title>CalCare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
          <Header/>
          <main>
              <Swiper
                  spaceBetween={50}
                  slidesPerView={1}
                  autoplay={true}
                  onSlideChange={() => console.log('slide change')}
                  onSwiper={(swiper) => console.log(swiper)}
              >
                  <SwiperSlide className={cls.swiperik}>Slide 1</SwiperSlide>
                  <SwiperSlide className={cls.swiperik}>Slide 2</SwiperSlide>
                  <SwiperSlide className={cls.swiperik}>Slide 3</SwiperSlide>
                  <SwiperSlide className={cls.swiperik}>Slide 4</SwiperSlide>
              </Swiper>
          </main>
    </>
  )
}
// export async function getServerSideProps(context) {
//   return {
//     props: {}, // will be passed to the page component as props
//   }
// }